# ~/.tmux.conf

# Options to make tmux feel more like a modern default terminal mux
set -g mouse on
set -g history-limit 1000000
set -g default-shell "/home/scottfo/.cargo/bin/nu"
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:Tc'
set -g base-index 1
set -g renumber-windows on
set -g allow-rename off
set -g automatic-rename on
set -g automatic-rename-format "Tab #I"

# Configure the catppuccin plugin
set -g @catppuccin_flavor "macchiato"
# set -g @catppuccin_window_status_style "rounded"
# set -g @catppuccin_window_number ""
# set -g @catppuccin_window_current_number ""
set -g @catppuccin_window_text " Tab #I"
set -g @catppuccin_window_current_text " Tab #I"

# Load catppuccin
source-file "/home/scottfo/.config/tmux/plugins/catppuccin/tmux/catppuccin_options_tmux.conf"
source-file "/home/scottfo/.config/tmux/plugins/catppuccin/tmux/catppuccin_tmux.conf"
# For TPM, instead use `run ~/.tmux/plugins/tmux/catppuccin.tmux`

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
